### ISSUE TITLE
Level 3 lagging, too

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#187]
Just noticed that a vast majority of level 3 entities are lagging by more than a day, too. At least for the U.S.

**Comment by eguidotti** [comment]
Fixed, the updates should be more timely now. Thanks!

**Comment by kenshermock** [comment]
Thank you, Emanuele. It seems that something is still wrong. In the level 3 dataset, Maryland (the state I am in) reports no new cases since December 5.

From: Emanuele Guidotti ***@***.***>
Reply-To: covid19datahub/COVID19 ***@***.***>
Date: Tuesday, December 14, 2021 at 15:52
To: covid19datahub/COVID19 ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Subject: Re: [covid19datahub/COVID19] Level 3 lagging, too (Issue #187)


      External Email - Use Caution





Fixed, the updates should be more timely now. Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcovid19datahub%2FCOVID19%2Fissues%2F187%23issuecomment-993989011&data=04%7C01%7Cken%40jhmi.edu%7C9b590da44776427b50c408d9bf43a9f1%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751119600218954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8IP70ulO0XTabZblofTomerDBbW2sD1YPykZPQIwGUE%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB4MMYDNWW244A6GPFOV5I3UQ6VBJANCNFSM5KAAYPJA&data=04%7C01%7Cken%40jhmi.edu%7C9b590da44776427b50c408d9bf43a9f1%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751119600228947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=It3pYEq4yDFb3hQ64QmtOCD%2FWuQl6KY2Z5WeIS9VE6k%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cken%40jhmi.edu%7C9b590da44776427b50c408d9bf43a9f1%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751119600228947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P6QoosSCBuk23BAfcy8Y8GCIQAdhw298KS7Wn8tbsAo%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cken%40jhmi.edu%7C9b590da44776427b50c408d9bf43a9f1%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751119600238938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TQu6SmTrNUtvn%2F04up%2BOw8sL2uwbRgS6puGPhpi4QFw%3D&reserved=0>.

**Comment by eguidotti** [comment]
See https://github.com/covid19datahub/COVID19/issues/186

**Comment by kenshermock** [comment]
Hi Emanuele,

I believe I found the source of the Maryland data problem: https://www.baltimoresun.com/coronavirus/bs-md-maryland-health-department-covid-data-cyberattack-20211213-d6t2fqiisffpte7xmuzxm5dudi-story.html

From: Emanuele Guidotti ***@***.***>
Reply-To: covid19datahub/COVID19 ***@***.***>
Date: Tuesday, December 14, 2021 at 15:52
To: covid19datahub/COVID19 ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Subject: Re: [covid19datahub/COVID19] Level 3 lagging, too (Issue #187)


      External Email - Use Caution





Fixed, the updates should be more timely now. Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcovid19datahub%2FCOVID19%2Fissues%2F187%23issuecomment-993989011&data=04%7C01%7Cken%40jhmi.edu%7C9b590da44776427b50c408d9bf43a9f1%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751119600218954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8IP70ulO0XTabZblofTomerDBbW2sD1YPykZPQIwGUE%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB4MMYDNWW244A6GPFOV5I3UQ6VBJANCNFSM5KAAYPJA&data=04%7C01%7Cken%40jhmi.edu%7C9b590da44776427b50c408d9bf43a9f1%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751119600228947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=It3pYEq4yDFb3hQ64QmtOCD%2FWuQl6KY2Z5WeIS9VE6k%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cken%40jhmi.edu%7C9b590da44776427b50c408d9bf43a9f1%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751119600228947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P6QoosSCBuk23BAfcy8Y8GCIQAdhw298KS7Wn8tbsAo%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cken%40jhmi.edu%7C9b590da44776427b50c408d9bf43a9f1%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751119600238938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TQu6SmTrNUtvn%2F04up%2BOw8sL2uwbRgS6puGPhpi4QFw%3D&reserved=0>.

**Comment by eguidotti** [comment]
Hi Ken, yes they also confirmed the same thing https://github.com/nytimes/covid-19-data/issues/649
Thanks!
