### ISSUE TITLE
Data missing from Portugal

### ISSUE THREAD

**Issue by susanapsilva** [covid19datahub/COVID19#192]
Data from Portugal is missing since 22/12/2021. Could you please check that out.
Thanks a lot.

**Comment by eguidotti** [comment]
Fixed, thanks!

**Comment by susanapsilva** [comment]
Thanks a lot.


> Fixed, thanks!

**Comment by susanapsilva** [comment]
Tests data are still missing since the end of 2021@eguidotti

**Comment by eguidotti** [comment]
Hi @susanapsilva, I checked and it seems to me that also the test data are up-to-date.
I changed nothing, so I guess it was only a temporary issue. 
Don't hesitate to let me know if you find anything else!
Thanks

**Comment by susanapsilva** [comment]
Thanks a lot.
Best,
Susana

Emanuele Guidotti ***@***.***> escreveu no dia terça,
11/01/2022 à(s) 14:06:
